project:
  type: website
  execute-dir: project

filters: 
  - algxpar-quarto
  - cap-filters.lua
  - runenv.lua

algxpar:
  algorithm-title: "Algoritmo"
  algorithm-prefix: "Algoritmo"

# Opções gerais
lang: pt-BR
number-sections: false
toc: true
crossref: 
  lst-title: Código
  lst-prefix: Código
  # prf-prefix: "Resposta"
bibliography: references.bib
biblio-style: abnt
syntax-definitions: 
  - terminal.xml


website:
  announcement: 
    icon: exclamation-octagon
    dismissable: false
    content: "**Atenção** - Este site  está em construção. As informações ainda estão incompletas!"
    type: danger
    position: below-navbar

  google-analytics: "G-0NHDE9GGJP"

  title: "Algoritmos & Programação"
  navbar:
    # logo: figuras/cap.png
    left:
      - text: Algoritmos
        href: algoritmos/index.qmd
      - text: Linguagem C
        href: linguagem-c/index.qmd
      - text: Problemas propostos
        href: problemas-algoritmos/index.qmd
    right:
      - sobre.qmd
      - icon: github
        href: https://jandermoreira.github.io

  sidebar:
    - id: principal
      background: light
      contents: 
      - text: "---"
      # - sidebar:algoritmos

    - id: algoritmos
      style: "docked"
      collapse-level: 2
      background: light
      contents: 
        - section: "Representação e uso de algoritmos"
          contents:
            - algoritmos/index.qmd
            - algoritmos/formalizacao.qmd
            # - algoritmos/desenvolvimento-basico-e-codificacao.qmd
            # - algoritmos/execucao-condicional.qmd
            # - algoritmos/desenvolvimento-com-condicionais-e-codificacao.qmd
        - section: "Processamento de sequências de dados"
          contents:
            - algoritmos/processamento-basico-de-sequencias-de-dados.qmd
            - algoritmos/desenvolvimento-de-algoritmos-para-processamento-de-sequencias.qmd
        - section: "Desenvolvimento e organização de algoritmos"
          contents:
        #     - algoritmos/desenvolvimento-por-refinamentos-sucessivos.qmd
        #     - algoritmos/testes-de-mesa.qmd
            - algoritmos/modularizacao.qmd
            - algoritmos/desenvolvimento-com-modularizacao.qmd
        # - section: "Representação de dados estruturados"
        #   contents: 
        #     - algoritmos/cadeias-de-caracteres.qmd
        #     - algoritmos/dados-compostos-registros.qmd
        #     - algoritmos/dados-compostos-vetores.qmd
        #     - algoritmos/dados-compostos-matrizes.qmd
        # - section: "Desenvolvimento com arquivos"
        #   contents: 
        #     - algoritmos/manipulacao-de-arquivos-de-registros.qmd
        # - section: "Recursividade"
        #   contents:
        #     - algoritmos/recursividade.qmd

    - id: c
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - section: "Programação básica"
          contents:
          - linguagem-c/index.qmd  # título real: introducao-a-linguagem-c.qmd
          - linguagem-c/tipos-de-dados.qmd
          - linguagem-c/variaveis-identificadores-e-leitura.qmd
          - linguagem-c/expressoes-aritmeticas.qmd
          - linguagem-c/expressoes-relacionais-e-logicas.qmd

        - section: "Controle de fluxo simples"
          contents:
          - linguagem-c/execucao-condicional-com-if.qmd
          - linguagem-c/execucao-condicional-com-switch.qmd

        - section: "Organização geral do código"
          contents:
          - linguagem-c/escopo-basico-de-declaracoes.qmd
          - linguagem-c/organizacao-do-codigo-fonte.qmd
          # - linguagem-c/define.qmd

        - section: "Controle de repetição do fluxo"
          contents:
          - linguagem-c/repeticoes-com-while.qmd
          - linguagem-c/repeticoes-com-for.qmd
          - linguagem-c/repeticoes-com-do-while.qmd
          - linguagem-c/desvirtuacao-das-repeticoes.qmd

        - section: "Cadeias de caracteres"
          contents:
          - linguagem-c/dados-textuais.qmd
          - linguagem-c/manipulacao-de-dados-textuais.qmd

        - section: "Modularização e memória"
          contents:
          - linguagem-c/funcoes.qmd
          - linguagem-c/procedimentos.qmd
          - linguagem-c/regras-de-escopo-com-modularizacao.qmd
          - linguagem-c/parametros-de-funcoes.qmd

        - section: "Acesso à memória"
          contents:
          - linguagem-c/enderecamento-de-memoria-e-ponteiros.qmd
          # - linguagem-c/alocacao-dinamica-de-memoria.qmd

        - section: "Estruturação de dados"
          contents:
          - linguagem-c/dados-com-struct.qmd
          - linguagem-c/dados-em-vetores.qmd
          # - linguagem-c/modularizacao-com-vetores.qmd
          # - linguagem-c/dados-em-matrizes.qmd
          # - linguagem-c/modularizacao-com-matrizes.qmd

        - section: "Manipulação de arquivos"
          contents:
          - linguagem-c/arquivos-texto.qmd
          # - linguagem-c/arquivos-binarios.qmd

        # - section: "Recursividade"
        #   contents:
        #     - linguagem-c/recursividade.qmd

        # - section: "Organização avançada do código"
        #   contents:
        #   - linguagem-c/organizacao-do-codigo-separado.qmd

    - id: problemas
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - problemas-algoritmos/index.qmd  #título real: introducao aos problemas
        - section: "Condicionais"
          contents:
            - problemas-algoritmos/condicionais-basicos.qmd


format:
  html:
    theme: yeti  # materia yeti zephyr
    css: book.css
    toc: true
    fontsize: 12pt
    number-depth: 3
    toc-title: "Nesta página:"
    toc-depth: 3
    highlight-style: tango
    code-block-border-left: true
    fig-align: center
    # fig-responsive: false
    fig-cap-location: bottom
